aws/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^vpc$', VpcListView.as_view(), name='vpc-list'),
    url(r'^vpc/(?P<pk>\d+)/$', VpcDetailView.as_view(), name='crud-Vpc-detail'),
    url(r'^vpc/(?P<pk>\d+)/graphic/$', VpcGraphicView.as_view(), name='graphic-Vpc-detail'),
    url(r'^$', ProfileListView.as_view(), name='profile-list'),
    url(r'^profile/(?P<pk>\d+)/$', ProfileDetailView.as_view(), name='crud-Profile-detail'),
    url(r'^subnet/(?P<pk>\d+)/$', SubnetDetailView.as_view(), name='crud-Subnet-detail'),
    url(r'^ec2/(?P<pk>\d+)/$', Ec2InstanceDetailView.as_view(), name='crud-Ec2Instance-detail'),
    url(r'^rds/(?P<pk>\d+)/$', DbInstanceDetailView.as_view(), name='crud-DbInstance-detail'),
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^daws/', include('aws.urls')),
    url(r'^wildcardenv/', include('wildcardenv.urls')),
]

wildcardenv/models.py
from django.db import models
from django.urls import reverse


class BaseModel():
    def __str__(self):
        if not self.name:
            return 'Untitled %s' % (self.__class__.__name__)
        return self.name

    def get_absolute_url(self):
        return reverse("crud-%s-detail" % (self.__class__.__name__), args=(self.id,))

    def get_fields(self):
        fields = []
        for field in self.__class__._meta.fields:
            fields.append((field.name, getattr(self, field.name), field.is_relation))

        # return [(field.name, field.value_from_object(self)) for field in self.__class__._meta.fields]
        return fields

class Template(BaseModel, models.Model):
    name = models.CharField(max_length=255)
    body = models.TextField(blank=True, null=False)

class Environment(BaseModel, models.Model):
    name = models.CharField(max_length=255)
    template = models.ForeignKey(Template, blank=True, null=True, related_name='environments', on_delete=models.CASCADE)
    stack_id = models.CharField(blank=True, null=False, max_length=32)

work/models.py
from django.db import models

class Client(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name

templates/projects/client_detail.html
{% extends "base.html" %}

{% block content %}

    <table class="table">
        <tbody>
            <tr><th>Name</th></tr>
            <tr><td>{{ object.name }}</td></tr>
        </tbody>
    </table>

    {% include "object_list.html" with header="Projects" object_list=object.project_set.all %}

{% endblock %}

templates/projects/environment_detail.html
{% extends "base.html" %}

{% block content %}

    <table class="table">
        <tbody>
            <tr><th>Name</th></tr>
            <tr><td>{{ object.name }}</td></tr>

            <tr><th>Project</th></tr>
            <tr class="scollink"><td>{% include "object_link.html" with object=object.project %}</td></tr>
        </tbody>
    </table>

{% endblock %}

templates/projects/home.html
{% extends "base.html" %}

{% block content %}


    <table class="table">
        <thead>
            <tr>
                <th>Home</th>
            </tr>
        </thead>
        <tbody>
            <tr class="scollink">
                <td><a href="/projects/clients">Clients</a>
            </tr>
            <tr class="scollink">
                <td><a href="/projects/products">Products</a>
            </tr>
            <tr class="scollink">
                <td><a href="/projects/projects">Projects</a>
            </tr>
            <tr class="scollink">
                <td><a href="/projects/environments">Environments</a>
            </tr>
        </tbody>
    </table>

{% endblock %}

templates/projects/product_detail.html
{% extends "base.html" %}

{% block content %}

    <table class="table">
        <tbody>
            <tr><th>Name</th></tr>
            <tr><td>{{ object.name }}</td></tr>
        </tbody>
    </table>

    {% include "object_list.html" with header="Projects" object_list=object.project_set.all %}

{% endblock %}

templates/projects/project_detail.html
{% extends "base.html" %}

{% block content %}

    <table class="table">
        <tbody>
            <tr><th>Name</th></tr>
            <tr><td>{{ object.name }}</td></tr>

            <tr><th>Client</th></tr>
            <tr class="scollink"><td>{% include "object_link.html" with object=object.client %}</td></tr>

        </tbody>
    </table>

    {% include "object_list.html" with header="Environments" object_list=object.environment_set.all %}

{% endblock %}